version: '2'
services:
  api:
    build: ./api
    container_name: api
    restart: "no"
    environment:
      - MASTER_NODE=True

  web:
    build: ./web
    container_name: web
    restart: "no"
    links:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./web/dist:/usr/share/nginx/www:ro

  mongodb:
    image: "mongo:3"
    container_name: mongodb
    ports:
       - "27017:27017"
    tty: true
